baseURL = 'https://kmj-007.github.io/learning-log/'
languageCode = 'en-us'
title = "Karan's Notes"


# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

[params]
  # source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/KMJ-007/learning-log'

  # 'Edit this page' links
  BookEditPath = 'edit/main'
  
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

  BookServiceWorker = true 

  bookCollapseSection = false
